# -*- coding: utf-8 -*-
"""TinyMLAssignment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tAn2SiDsYKx0MkelbD2u6-ZUNFWCDQZK
"""

import numpy as np
import tensorflow as tf
from tensorflow import keras
import matplotlib.pyplot as plt

# ===== 1. Generate Data =====
np.random.seed(42)
SAMPLES = 1000
x_values = np.random.uniform(0, 2 * np.pi, SAMPLES).astype(np.float32)
x_values = x_values / (2 * np.pi)
y_values = np.cos(x_values).astype(np.float32)
y_values += 0.1 * np.random.randn(SAMPLES).astype(np.float32)
indices = np.arange(SAMPLES)
np.random.shuffle(indices)
x_values = x_values[indices]
y_values = y_values[indices]
# Split: 60% train, 20% validation, 20% test
TRAIN = int(0.6 * SAMPLES)
VAL = int(0.8 * SAMPLES)
x_train, y_train = x_values[:TRAIN], y_values[:TRAIN]
x_val, y_val = x_values[TRAIN:VAL], y_values[TRAIN:VAL]
x_test, y_test = x_values[VAL:], y_values[VAL:]

# ===== 2. Build Model =====
model = keras.Sequential([
keras.layers.Dense(16, activation='relu', input_shape=(1,)),
keras.layers.Dense(16, activation='relu'),
keras.layers.Dense(1)
])
model.compile(optimizer='adam', loss='mse', metrics=['mae'])
model.summary()

history = model.fit(x_train, y_train,
epochs=500, batch_size=64,
validation_data=(x_val, y_val),
verbose=1)

# ===== 4. Evaluate =====
loss, mae = model.evaluate(x_test, y_test)
print(f"Test MAE: {mae:.4f}")

# Plot predictions vs actual
predictions = model.predict(x_test)
plt.scatter(x_test, y_test, label='Actual', s=5)
plt.scatter(x_test, predictions, label='Predicted', s=5)
plt.legend()
plt.title('Cosine Wave Prediction')
plt.show()

# ===== 5. Convert to TFLite =====
converter = tf.lite.TFLiteConverter.from_keras_model(model)
# Full integer quantization
converter.optimizations = [tf.lite.Optimize.DEFAULT]
def representative_dataset():
  for i in range(100):
    yield [np.array([[x_train[i]]], dtype=np.float32)]

converter.representative_dataset = representative_dataset
converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]
converter.inference_input_type = tf.int8
converter.inference_output_type = tf.int8
tflite_model = converter.convert()

# Save
with open('cosine_int8.tflite', 'wb') as f:
  f.write(tflite_model)
print(f"Model size: {len(tflite_model)} bytes")

# ===== 6. Run Quantized TFLite Model =====
interpreter = tf.lite.Interpreter(model_path="cosine_int8.tflite")
interpreter.allocate_tensors()
input_details = interpreter.get_input_details()
output_details = interpreter.get_output_details()
input_scale, input_zero_point = input_details[0]['quantization']
output_scale, output_zero_point = output_details[0]['quantization']
int8_predictions = []
for x in x_test:
    x_input = np.array([[x]], dtype=np.float32)
    x_quantized = (x_input / input_scale + input_zero_point).astype(np.int8)
    interpreter.set_tensor(input_details[0]['index'], x_quantized)
    interpreter.invoke()
    output_quantized = interpreter.get_tensor(output_details[0]['index'])
    output = (output_quantized.astype(np.float32) - output_zero_point) * output_scale
    int8_predictions.append(output[0][0])
int8_predictions = np.array(int8_predictions)
quantized_mae = np.mean(np.abs(int8_predictions - y_test))
print("Quantized MAE:", quantized_mae)
float_predictions = model.predict(x_test).flatten()
sorted_indices = np.argsort(x_test)
plt.figure(figsize=(10, 5))
plt.plot(
    x_test[sorted_indices],
    y_test[sorted_indices],
    label='Ground Truth'
)
plt.plot(
    x_test[sorted_indices],
    float_predictions[sorted_indices],
    label='Float Model'
)
plt.plot(
    x_test[sorted_indices],
    int8_predictions[sorted_indices],
    label='INT8 Quantized Model'
)
plt.title('Cosine Model: Float vs INT8')
plt.xlabel('x')
plt.ylabel('y')
plt.legend()
plt.show()

# ===== 6. Convert to C Header =====
import binascii
hex_data = binascii.hexlify(tflite_model).decode('ascii')
c_array = ', '.join([
    '0x' + hex_data[i:i+2]
    for i in range(0, len(hex_data), 2)
])
header = f'''#ifndef COSINE_MODEL_H
#define COSINE_MODEL_H
#include <cstddef>
#include <cstdint>
alignas(8) const unsigned char g_model[] = {{
{c_array}
}};
const unsigned int g_model_len = {len(tflite_model)};
#endif // COSINE_MODEL_H
'''
with open('cosine_model.h', 'w') as f:
    f.write(header)
print("C header generated: cosine_model.h")